//! Every token and node kind of the syntax tree, in one enum so rowan can store it as a `u16`. The
//! keywords are the words the grammar looks for, in one sorted table the lexer searches.

macro_rules! syntax_kinds {
    ($($name:ident),* $(,)?) => {
        /// The kind of a token or a node.
        #[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
        #[repr(u16)]
        #[allow(non_camel_case_types, clippy::upper_case_acronyms)]
        pub enum SyntaxKind {
            $($name),*
        }

        impl SyntaxKind {
            /// Every kind in declaration order; the index is the raw value.
            pub const ALL: &'static [SyntaxKind] = &[$(SyntaxKind::$name),*];

            /// The name of the variant, as the tree dump prints it.
            pub fn name(self) -> &'static str {
                match self {
                    $(SyntaxKind::$name => stringify!($name)),*
                }
            }
        }
    };
}

syntax_kinds! {
    // Trivia
    WHITESPACE,
    LINE_COMMENT,
    BLOCK_COMMENT,

    // A character no dialect knows, and what the parser sees past the last token, which is never in a tree.
    UNKNOWN,
    EOF,

    // Names, literals, parameters and variables
    IDENT,
    QUOTED_IDENT,
    BACKTICK_IDENT,
    BRACKET_IDENT,
    STRING,
    ESCAPE_STRING,
    NATIONAL_STRING,
    UNICODE_STRING,
    BIT_STRING,
    HEX_STRING,
    DOLLAR_STRING,
    INT_NUMBER,
    FLOAT_NUMBER,
    PARAM,
    VARIABLE,
    SYSTEM_VARIABLE,

    // What a script runner reads besides SQL
    DELIMITER_VALUE,
    CUSTOM_DELIMITER,
    META_COMMAND,
    COPY_DATA,

    // Punctuation
    LPAREN,
    RPAREN,
    LBRACKET,
    RBRACKET,
    LBRACE,
    RBRACE,
    COMMA,
    SEMICOLON,
    DOT,
    COLON,
    DOUBLE_COLON,
    COLON_EQ,

    // Operators
    STAR,
    PLUS,
    MINUS,
    SLASH,
    PERCENT,
    CARET,
    EQ,
    EQ_EQ,
    NEQ,
    BANG_EQ,
    LT,
    GT,
    LTE,
    GTE,
    NULL_SAFE_EQ,
    PIPE_PIPE,
    AMP_AMP,
    PIPE,
    AMP,
    TILDE,
    BANG,
    SHL,
    SHR,
    ARROW,
    LONG_ARROW,
    FAT_ARROW,
    HASH,
    HASH_ARROW,
    HASH_LONG_ARROW,
    HASH_MINUS,
    AT_GT,
    LT_AT,
    AT_AT,
    AT,
    QUESTION,
    QUESTION_PIPE,
    QUESTION_AMP,
    TILDE_STAR,
    BANG_TILDE,
    BANG_TILDE_STAR,
    CUSTOM_OP,

    // Keywords
    ABORT_KW,
    ABSENT_KW,
    ACTION_KW,
    ADD_KW,
    AFTER_KW,
    AGAINST_KW,
    ALGORITHM_KW,
    ALL_KW,
    ALTER_KW,
    ALWAYS_KW,
    ANALYZE_KW,
    AND_KW,
    ANY_KW,
    ARRAY_KW,
    AS_KW,
    ASC_KW,
    ASYMMETRIC_KW,
    AT_KW,
    ATOMIC_KW,
    ATTACH_KW,
    AUTHORIZATION_KW,
    AUTOINCREMENT_KW,
    AUTO_INCREMENT_KW,
    BEFORE_KW,
    BEGIN_KW,
    BETWEEN_KW,
    BINARY_KW,
    BOTH_KW,
    BREADTH_KW,
    BY_KW,
    CALL_KW,
    CASCADE_KW,
    CASCADED_KW,
    CASE_KW,
    CAST_KW,
    CHAIN_KW,
    CHANGE_KW,
    CHAR_KW,
    CHARACTER_KW,
    CHARSET_KW,
    CHECK_KW,
    CHECKPOINT_KW,
    CLOSE_KW,
    CLUSTER_KW,
    COLLATE_KW,
    COLUMN_KW,
    COLUMNS_KW,
    COMMENT_KW,
    COMMIT_KW,
    COMMITTED_KW,
    CONCURRENTLY_KW,
    CONDITION_KW,
    CONDITIONAL_KW,
    CONFLICT_KW,
    CONSTRAINT_KW,
    CONTINUE_KW,
    COPY_KW,
    CREATE_KW,
    CROSS_KW,
    CUBE_KW,
    CURRENT_KW,
    CURRENT_CATALOG_KW,
    CURRENT_DATE_KW,
    CURRENT_ROLE_KW,
    CURRENT_SCHEMA_KW,
    CURRENT_TIME_KW,
    CURRENT_TIMESTAMP_KW,
    CURRENT_USER_KW,
    CURSOR_KW,
    CYCLE_KW,
    DATA_KW,
    DATABASE_KW,
    DATE_KW,
    DAY_KW,
    DAY_HOUR_KW,
    DAY_MICROSECOND_KW,
    DAY_MINUTE_KW,
    DAY_SECOND_KW,
    DEALLOCATE_KW,
    DECLARE_KW,
    DEFAULT_KW,
    DEFERRABLE_KW,
    DEFERRED_KW,
    DEFINER_KW,
    DELAYED_KW,
    DELETE_KW,
    DELIMITER_KW,
    DEPTH_KW,
    DESC_KW,
    DESCRIBE_KW,
    DETACH_KW,
    DIAGNOSTICS_KW,
    DISCARD_KW,
    DISTINCT_KW,
    DISTINCTROW_KW,
    DIV_KW,
    DO_KW,
    DOMAIN_KW,
    DOUBLE_KW,
    DROP_KW,
    DUPLICATE_KW,
    EACH_KW,
    ELSE_KW,
    ELSEIF_KW,
    ELSIF_KW,
    EMPTY_KW,
    ENCODING_KW,
    END_KW,
    ENFORCED_KW,
    ENGINE_KW,
    ERROR_KW,
    ESCAPE_KW,
    EVENT_KW,
    EXCEPT_KW,
    EXCLUDE_KW,
    EXCLUDING_KW,
    EXCLUSIVE_KW,
    EXECUTE_KW,
    EXISTS_KW,
    EXIT_KW,
    EXPLAIN_KW,
    EXTENSION_KW,
    FAIL_KW,
    FALSE_KW,
    FETCH_KW,
    FILTER_KW,
    FIRST_KW,
    FLUSH_KW,
    FOLLOWING_KW,
    FOLLOWS_KW,
    FOR_KW,
    FORCE_KW,
    FOREIGN_KW,
    FORMAT_KW,
    FROM_KW,
    FULL_KW,
    FULLTEXT_KW,
    FUNCTION_KW,
    GENERATED_KW,
    GET_KW,
    GLOB_KW,
    GLOBAL_KW,
    GRANT_KW,
    GROUP_KW,
    GROUPING_KW,
    GROUPS_KW,
    HANDLER_KW,
    HAVING_KW,
    HIGH_PRIORITY_KW,
    HOUR_KW,
    HOUR_MICROSECOND_KW,
    HOUR_MINUTE_KW,
    HOUR_SECOND_KW,
    IDENTITY_KW,
    IF_KW,
    IGNORE_KW,
    ILIKE_KW,
    IMMEDIATE_KW,
    IN_KW,
    INCLUDE_KW,
    INCLUDING_KW,
    INDEX_KW,
    INDEXED_KW,
    INHERITS_KW,
    INITIALLY_KW,
    INNER_KW,
    INOUT_KW,
    INSERT_KW,
    INSTEAD_KW,
    INTERSECT_KW,
    INTERVAL_KW,
    INTO_KW,
    INVISIBLE_KW,
    INVOKER_KW,
    IS_KW,
    ISNULL_KW,
    ISOLATION_KW,
    ITERATE_KW,
    JOIN_KW,
    JSON_KW,
    KEEP_KW,
    KEY_KW,
    KEYS_KW,
    KILL_KW,
    LANGUAGE_KW,
    LAST_KW,
    LATERAL_KW,
    LEADING_KW,
    LEAVE_KW,
    LEFT_KW,
    LEVEL_KW,
    LIKE_KW,
    LIMIT_KW,
    LISTEN_KW,
    LOAD_KW,
    LOCAL_KW,
    LOCALTIME_KW,
    LOCALTIMESTAMP_KW,
    LOCK_KW,
    LOCKED_KW,
    LOOP_KW,
    LOW_PRIORITY_KW,
    MATCH_KW,
    MATCHED_KW,
    MATERIALIZED_KW,
    MEMBER_KW,
    MERGE_KW,
    MICROSECOND_KW,
    MINUTE_KW,
    MINUTE_MICROSECOND_KW,
    MINUTE_SECOND_KW,
    MOD_KW,
    MODE_KW,
    MODIFY_KW,
    MONTH_KW,
    MOVE_KW,
    NAMES_KW,
    NATIONAL_KW,
    NATURAL_KW,
    NESTED_KW,
    NEXT_KW,
    NO_KW,
    NOT_KW,
    NOTHING_KW,
    NOTIFY_KW,
    NOTNULL_KW,
    NOWAIT_KW,
    NULL_KW,
    NULLS_KW,
    OBJECT_KW,
    OF_KW,
    OFFSET_KW,
    OMIT_KW,
    ON_KW,
    ONLY_KW,
    OPEN_KW,
    OPERATOR_KW,
    OPTIMIZE_KW,
    OPTION_KW,
    OR_KW,
    ORDER_KW,
    ORDINALITY_KW,
    OTHERS_KW,
    OUT_KW,
    OUTER_KW,
    OVER_KW,
    OVERLAPS_KW,
    OVERRIDING_KW,
    OWNED_KW,
    OWNER_KW,
    PARTITION_KW,
    PASSING_KW,
    PATH_KW,
    PERCENT_KW,
    PERSIST_KW,
    PERSIST_ONLY_KW,
    PLACING_KW,
    PLAN_KW,
    PRAGMA_KW,
    PRECEDES_KW,
    PRECEDING_KW,
    PRECISION_KW,
    PREPARE_KW,
    PRIMARY_KW,
    PROCEDURE_KW,
    QUALIFY_KW,
    QUARTER_KW,
    QUERY_KW,
    QUICK_KW,
    QUOTES_KW,
    RANGE_KW,
    READ_KW,
    RECURSIVE_KW,
    REFERENCES_KW,
    REFERENCING_KW,
    REFRESH_KW,
    REGEXP_KW,
    REINDEX_KW,
    RELEASE_KW,
    RENAME_KW,
    REPAIR_KW,
    REPEAT_KW,
    REPEATABLE_KW,
    REPLACE_KW,
    RESET_KW,
    RESIGNAL_KW,
    RESTART_KW,
    RESTRICT_KW,
    RETURN_KW,
    RETURNING_KW,
    RETURNS_KW,
    REVOKE_KW,
    RIGHT_KW,
    RLIKE_KW,
    ROLE_KW,
    ROLLBACK_KW,
    ROLLUP_KW,
    ROW_KW,
    ROWID_KW,
    ROWS_KW,
    SAVEPOINT_KW,
    SCALAR_KW,
    SCHEMA_KW,
    SEARCH_KW,
    SECOND_KW,
    SECOND_MICROSECOND_KW,
    SECURITY_KW,
    SELECT_KW,
    SEPARATOR_KW,
    SEQUENCE_KW,
    SERIALIZABLE_KW,
    SESSION_KW,
    SESSION_USER_KW,
    SET_KW,
    SETOF_KW,
    SETS_KW,
    SHARE_KW,
    SHOW_KW,
    SIGNAL_KW,
    SIGNED_KW,
    SIMILAR_KW,
    SKIP_KW,
    SOME_KW,
    SOUNDS_KW,
    SPATIAL_KW,
    SQL_KW,
    SQL_CALC_FOUND_ROWS_KW,
    START_KW,
    STATEMENT_KW,
    STDIN_KW,
    STDOUT_KW,
    STORAGE_KW,
    STORED_KW,
    STRAIGHT_JOIN_KW,
    STRICT_KW,
    SYMMETRIC_KW,
    SYSTEM_USER_KW,
    TABLE_KW,
    TABLESAMPLE_KW,
    TEMP_KW,
    TEMPORARY_KW,
    THEN_KW,
    TIES_KW,
    TIME_KW,
    TIMESTAMP_KW,
    TO_KW,
    TRAILING_KW,
    TRANSACTION_KW,
    TRIGGER_KW,
    TRUE_KW,
    TRUNCATE_KW,
    TYPE_KW,
    UNBOUNDED_KW,
    UNCOMMITTED_KW,
    UNCONDITIONAL_KW,
    UNION_KW,
    UNIQUE_KW,
    UNKNOWN_KW,
    UNLISTEN_KW,
    UNLOCK_KW,
    UNLOGGED_KW,
    UNSIGNED_KW,
    UNTIL_KW,
    UPDATE_KW,
    USE_KW,
    USER_KW,
    USING_KW,
    VACUUM_KW,
    VALUE_KW,
    VALUES_KW,
    VARIADIC_KW,
    VARYING_KW,
    VIEW_KW,
    VIRTUAL_KW,
    VISIBLE_KW,
    WEEK_KW,
    WHEN_KW,
    WHERE_KW,
    WHILE_KW,
    WINDOW_KW,
    WITH_KW,
    WITHIN_KW,
    WITHOUT_KW,
    WORK_KW,
    WRAPPER_KW,
    WRITE_KW,
    XOR_KW,
    YEAR_KW,
    YEAR_MONTH_KW,
    ZEROFILL_KW,
    ZONE_KW,

    // Nodes
    SOURCE_FILE,
    ERROR,
    NAME,
    QUALIFIED_NAME,
    COLUMN_REF,
    WILDCARD,
    ALIAS,
    NAME_LIST,
    ACCOUNT_NAME,
    EMPTY_STMT,
    UNKNOWN_STMT,
    SELECT_STMT,
    INSERT_STMT,
    UPDATE_STMT,
    DELETE_STMT,
    MERGE_STMT,
    CREATE_TABLE_STMT,
    CREATE_INDEX_STMT,
    CREATE_VIEW_STMT,
    CREATE_SCHEMA_STMT,
    CREATE_SEQUENCE_STMT,
    CREATE_TYPE_STMT,
    CREATE_DOMAIN_STMT,
    CREATE_FUNCTION_STMT,
    CREATE_TRIGGER_STMT,
    CREATE_EXTENSION_STMT,
    CREATE_STMT,
    ALTER_TABLE_STMT,
    ALTER_STMT,
    DROP_STMT,
    RENAME_TABLE_STMT,
    TRUNCATE_STMT,
    BEGIN_STMT,
    COMMIT_STMT,
    ROLLBACK_STMT,
    SAVEPOINT_STMT,
    RELEASE_STMT,
    SET_STMT,
    SHOW_STMT,
    USE_STMT,
    EXPLAIN_STMT,
    PRAGMA_STMT,
    GRANT_STMT,
    REVOKE_STMT,
    COMMENT_STMT,
    COPY_STMT,
    PREPARE_STMT,
    EXECUTE_STMT,
    DEALLOCATE_STMT,
    CALL_STMT,
    DO_STMT,
    DELIMITER_STMT,
    META_COMMAND_STMT,
    REFRESH_STMT,
    LOCK_STMT,
    UNLOCK_STMT,
    ATTACH_STMT,
    DETACH_STMT,
    UTILITY_STMT,
    DECLARE_STMT,
    OPEN_STMT,
    FETCH_STMT,
    CLOSE_STMT,
    BLOCK,
    STATEMENT_LIST,
    LABEL,
    IF_STMT,
    ELSEIF_CLAUSE,
    CASE_STMT,
    LOOP_STMT,
    WHILE_STMT,
    REPEAT_STMT,
    LEAVE_STMT,
    ITERATE_STMT,
    RETURN_STMT,
    SIGNAL_STMT,
    GET_DIAGNOSTICS_STMT,
    SELECT,
    COMPOUND_SELECT,
    VALUES,
    TABLE_QUERY,
    PAREN_QUERY,
    WITH_CLAUSE,
    CTE,
    DISTINCT_CLAUSE,
    SELECT_LIST,
    SELECT_ITEM,
    INTO_CLAUSE,
    FROM_CLAUSE,
    WHERE_CLAUSE,
    GROUP_BY_CLAUSE,
    GROUPING_SET,
    HAVING_CLAUSE,
    WINDOW_CLAUSE,
    WINDOW_DEF,
    QUALIFY_CLAUSE,
    ORDER_BY_CLAUSE,
    ORDER_ITEM,
    LIMIT_CLAUSE,
    OFFSET_CLAUSE,
    FETCH_CLAUSE,
    LOCKING_CLAUSE,
    TABLE_REF,
    DERIVED_TABLE,
    TABLE_FUNCTION,
    JOIN_EXPR,
    PAREN_JOIN,
    ON_CLAUSE,
    USING_CLAUSE,
    INDEX_HINT,
    PARTITION_SELECTION,
    TABLESAMPLE_CLAUSE,
    LITERAL,
    TYPED_LITERAL,
    INTERVAL_EXPR,
    PARAMETER,
    VARIABLE_REF,
    FUNCTION_CALL,
    ARG_LIST,
    NAMED_ARG,
    FILTER_CLAUSE,
    WITHIN_GROUP_CLAUSE,
    OVER_CLAUSE,
    WINDOW_SPEC,
    PARTITION_BY_CLAUSE,
    FRAME_CLAUSE,
    CAST_EXPR,
    TYPECAST_EXPR,
    CASE_EXPR,
    WHEN_CLAUSE,
    ELSE_CLAUSE,
    BINARY_EXPR,
    PREFIX_EXPR,
    IS_EXPR,
    BETWEEN_EXPR,
    IN_EXPR,
    IN_LIST,
    LIKE_EXPR,
    MEMBER_OF_EXPR,
    EXISTS_EXPR,
    PAREN_EXPR,
    ROW_EXPR,
    ARRAY_EXPR,
    INDEX_EXPR,
    FIELD_EXPR,
    COLLATE_EXPR,
    AT_TIME_ZONE_EXPR,
    QUANTIFIED_EXPR,
    VALUE_FUNCTION,
    DEFAULT_EXPR,
    MATCH_AGAINST_EXPR,
    OPERATOR_NAME,
    JSON_KEY_VALUE,
    JSON_CLAUSE,
    JSON_TABLE_COLUMNS,
    JSON_TABLE_COLUMN,
    TYPE,
    TYPE_ARGS,
    SET_CLAUSE,
    ASSIGNMENT,
    ON_DUPLICATE_KEY_CLAUSE,
    UPSERT_CLAUSE,
    CONFLICT_TARGET,
    RETURNING_CLAUSE,
    MERGE_WHEN_CLAUSE,
    TABLE_ELEMENT_LIST,
    COLUMN_DEF,
    COLUMN_CONSTRAINT,
    TABLE_CONSTRAINT,
    REFERENCES_CLAUSE,
    INDEX_COLUMN_LIST,
    INDEX_COLUMN,
    TABLE_OPTION,
    TABLE_PARTITION_CLAUSE,
    PARTITION_DEF,
    LIKE_CLAUSE,
    ADD_COLUMN_ACTION,
    DROP_COLUMN_ACTION,
    ALTER_COLUMN_ACTION,
    MODIFY_COLUMN_ACTION,
    RENAME_COLUMN_ACTION,
    RENAME_TABLE_ACTION,
    ADD_CONSTRAINT_ACTION,
    DROP_CONSTRAINT_ACTION,
    ALTER_TABLE_ACTION,
    ENUM_VALUE_LIST,
    PARAM_LIST,
    PARAM_DEF,
    RETURNS_CLAUSE,
    ROUTINE_BODY,
    SET_ASSIGNMENT,
}

/// The keywords by their spelling in capitals, sorted for a binary search.
pub(crate) static KEYWORDS: &[(&str, SyntaxKind)] = &[
    ("ABORT", SyntaxKind::ABORT_KW),
    ("ABSENT", SyntaxKind::ABSENT_KW),
    ("ACTION", SyntaxKind::ACTION_KW),
    ("ADD", SyntaxKind::ADD_KW),
    ("AFTER", SyntaxKind::AFTER_KW),
    ("AGAINST", SyntaxKind::AGAINST_KW),
    ("ALGORITHM", SyntaxKind::ALGORITHM_KW),
    ("ALL", SyntaxKind::ALL_KW),
    ("ALTER", SyntaxKind::ALTER_KW),
    ("ALWAYS", SyntaxKind::ALWAYS_KW),
    ("ANALYZE", SyntaxKind::ANALYZE_KW),
    ("AND", SyntaxKind::AND_KW),
    ("ANY", SyntaxKind::ANY_KW),
    ("ARRAY", SyntaxKind::ARRAY_KW),
    ("AS", SyntaxKind::AS_KW),
    ("ASC", SyntaxKind::ASC_KW),
    ("ASYMMETRIC", SyntaxKind::ASYMMETRIC_KW),
    ("AT", SyntaxKind::AT_KW),
    ("ATOMIC", SyntaxKind::ATOMIC_KW),
    ("ATTACH", SyntaxKind::ATTACH_KW),
    ("AUTHORIZATION", SyntaxKind::AUTHORIZATION_KW),
    ("AUTOINCREMENT", SyntaxKind::AUTOINCREMENT_KW),
    ("AUTO_INCREMENT", SyntaxKind::AUTO_INCREMENT_KW),
    ("BEFORE", SyntaxKind::BEFORE_KW),
    ("BEGIN", SyntaxKind::BEGIN_KW),
    ("BETWEEN", SyntaxKind::BETWEEN_KW),
    ("BINARY", SyntaxKind::BINARY_KW),
    ("BOTH", SyntaxKind::BOTH_KW),
    ("BREADTH", SyntaxKind::BREADTH_KW),
    ("BY", SyntaxKind::BY_KW),
    ("CALL", SyntaxKind::CALL_KW),
    ("CASCADE", SyntaxKind::CASCADE_KW),
    ("CASCADED", SyntaxKind::CASCADED_KW),
    ("CASE", SyntaxKind::CASE_KW),
    ("CAST", SyntaxKind::CAST_KW),
    ("CHAIN", SyntaxKind::CHAIN_KW),
    ("CHANGE", SyntaxKind::CHANGE_KW),
    ("CHAR", SyntaxKind::CHAR_KW),
    ("CHARACTER", SyntaxKind::CHARACTER_KW),
    ("CHARSET", SyntaxKind::CHARSET_KW),
    ("CHECK", SyntaxKind::CHECK_KW),
    ("CHECKPOINT", SyntaxKind::CHECKPOINT_KW),
    ("CLOSE", SyntaxKind::CLOSE_KW),
    ("CLUSTER", SyntaxKind::CLUSTER_KW),
    ("COLLATE", SyntaxKind::COLLATE_KW),
    ("COLUMN", SyntaxKind::COLUMN_KW),
    ("COLUMNS", SyntaxKind::COLUMNS_KW),
    ("COMMENT", SyntaxKind::COMMENT_KW),
    ("COMMIT", SyntaxKind::COMMIT_KW),
    ("COMMITTED", SyntaxKind::COMMITTED_KW),
    ("CONCURRENTLY", SyntaxKind::CONCURRENTLY_KW),
    ("CONDITION", SyntaxKind::CONDITION_KW),
    ("CONDITIONAL", SyntaxKind::CONDITIONAL_KW),
    ("CONFLICT", SyntaxKind::CONFLICT_KW),
    ("CONSTRAINT", SyntaxKind::CONSTRAINT_KW),
    ("CONTINUE", SyntaxKind::CONTINUE_KW),
    ("COPY", SyntaxKind::COPY_KW),
    ("CREATE", SyntaxKind::CREATE_KW),
    ("CROSS", SyntaxKind::CROSS_KW),
    ("CUBE", SyntaxKind::CUBE_KW),
    ("CURRENT", SyntaxKind::CURRENT_KW),
    ("CURRENT_CATALOG", SyntaxKind::CURRENT_CATALOG_KW),
    ("CURRENT_DATE", SyntaxKind::CURRENT_DATE_KW),
    ("CURRENT_ROLE", SyntaxKind::CURRENT_ROLE_KW),
    ("CURRENT_SCHEMA", SyntaxKind::CURRENT_SCHEMA_KW),
    ("CURRENT_TIME", SyntaxKind::CURRENT_TIME_KW),
    ("CURRENT_TIMESTAMP", SyntaxKind::CURRENT_TIMESTAMP_KW),
    ("CURRENT_USER", SyntaxKind::CURRENT_USER_KW),
    ("CURSOR", SyntaxKind::CURSOR_KW),
    ("CYCLE", SyntaxKind::CYCLE_KW),
    ("DATA", SyntaxKind::DATA_KW),
    ("DATABASE", SyntaxKind::DATABASE_KW),
    ("DATE", SyntaxKind::DATE_KW),
    ("DAY", SyntaxKind::DAY_KW),
    ("DAY_HOUR", SyntaxKind::DAY_HOUR_KW),
    ("DAY_MICROSECOND", SyntaxKind::DAY_MICROSECOND_KW),
    ("DAY_MINUTE", SyntaxKind::DAY_MINUTE_KW),
    ("DAY_SECOND", SyntaxKind::DAY_SECOND_KW),
    ("DEALLOCATE", SyntaxKind::DEALLOCATE_KW),
    ("DECLARE", SyntaxKind::DECLARE_KW),
    ("DEFAULT", SyntaxKind::DEFAULT_KW),
    ("DEFERRABLE", SyntaxKind::DEFERRABLE_KW),
    ("DEFERRED", SyntaxKind::DEFERRED_KW),
    ("DEFINER", SyntaxKind::DEFINER_KW),
    ("DELAYED", SyntaxKind::DELAYED_KW),
    ("DELETE", SyntaxKind::DELETE_KW),
    ("DELIMITER", SyntaxKind::DELIMITER_KW),
    ("DEPTH", SyntaxKind::DEPTH_KW),
    ("DESC", SyntaxKind::DESC_KW),
    ("DESCRIBE", SyntaxKind::DESCRIBE_KW),
    ("DETACH", SyntaxKind::DETACH_KW),
    ("DIAGNOSTICS", SyntaxKind::DIAGNOSTICS_KW),
    ("DISCARD", SyntaxKind::DISCARD_KW),
    ("DISTINCT", SyntaxKind::DISTINCT_KW),
    ("DISTINCTROW", SyntaxKind::DISTINCTROW_KW),
    ("DIV", SyntaxKind::DIV_KW),
    ("DO", SyntaxKind::DO_KW),
    ("DOMAIN", SyntaxKind::DOMAIN_KW),
    ("DOUBLE", SyntaxKind::DOUBLE_KW),
    ("DROP", SyntaxKind::DROP_KW),
    ("DUPLICATE", SyntaxKind::DUPLICATE_KW),
    ("EACH", SyntaxKind::EACH_KW),
    ("ELSE", SyntaxKind::ELSE_KW),
    ("ELSEIF", SyntaxKind::ELSEIF_KW),
    ("ELSIF", SyntaxKind::ELSIF_KW),
    ("EMPTY", SyntaxKind::EMPTY_KW),
    ("ENCODING", SyntaxKind::ENCODING_KW),
    ("END", SyntaxKind::END_KW),
    ("ENFORCED", SyntaxKind::ENFORCED_KW),
    ("ENGINE", SyntaxKind::ENGINE_KW),
    ("ERROR", SyntaxKind::ERROR_KW),
    ("ESCAPE", SyntaxKind::ESCAPE_KW),
    ("EVENT", SyntaxKind::EVENT_KW),
    ("EXCEPT", SyntaxKind::EXCEPT_KW),
    ("EXCLUDE", SyntaxKind::EXCLUDE_KW),
    ("EXCLUDING", SyntaxKind::EXCLUDING_KW),
    ("EXCLUSIVE", SyntaxKind::EXCLUSIVE_KW),
    ("EXECUTE", SyntaxKind::EXECUTE_KW),
    ("EXISTS", SyntaxKind::EXISTS_KW),
    ("EXIT", SyntaxKind::EXIT_KW),
    ("EXPLAIN", SyntaxKind::EXPLAIN_KW),
    ("EXTENSION", SyntaxKind::EXTENSION_KW),
    ("FAIL", SyntaxKind::FAIL_KW),
    ("FALSE", SyntaxKind::FALSE_KW),
    ("FETCH", SyntaxKind::FETCH_KW),
    ("FILTER", SyntaxKind::FILTER_KW),
    ("FIRST", SyntaxKind::FIRST_KW),
    ("FLUSH", SyntaxKind::FLUSH_KW),
    ("FOLLOWING", SyntaxKind::FOLLOWING_KW),
    ("FOLLOWS", SyntaxKind::FOLLOWS_KW),
    ("FOR", SyntaxKind::FOR_KW),
    ("FORCE", SyntaxKind::FORCE_KW),
    ("FOREIGN", SyntaxKind::FOREIGN_KW),
    ("FORMAT", SyntaxKind::FORMAT_KW),
    ("FROM", SyntaxKind::FROM_KW),
    ("FULL", SyntaxKind::FULL_KW),
    ("FULLTEXT", SyntaxKind::FULLTEXT_KW),
    ("FUNCTION", SyntaxKind::FUNCTION_KW),
    ("GENERATED", SyntaxKind::GENERATED_KW),
    ("GET", SyntaxKind::GET_KW),
    ("GLOB", SyntaxKind::GLOB_KW),
    ("GLOBAL", SyntaxKind::GLOBAL_KW),
    ("GRANT", SyntaxKind::GRANT_KW),
    ("GROUP", SyntaxKind::GROUP_KW),
    ("GROUPING", SyntaxKind::GROUPING_KW),
    ("GROUPS", SyntaxKind::GROUPS_KW),
    ("HANDLER", SyntaxKind::HANDLER_KW),
    ("HAVING", SyntaxKind::HAVING_KW),
    ("HIGH_PRIORITY", SyntaxKind::HIGH_PRIORITY_KW),
    ("HOUR", SyntaxKind::HOUR_KW),
    ("HOUR_MICROSECOND", SyntaxKind::HOUR_MICROSECOND_KW),
    ("HOUR_MINUTE", SyntaxKind::HOUR_MINUTE_KW),
    ("HOUR_SECOND", SyntaxKind::HOUR_SECOND_KW),
    ("IDENTITY", SyntaxKind::IDENTITY_KW),
    ("IF", SyntaxKind::IF_KW),
    ("IGNORE", SyntaxKind::IGNORE_KW),
    ("ILIKE", SyntaxKind::ILIKE_KW),
    ("IMMEDIATE", SyntaxKind::IMMEDIATE_KW),
    ("IN", SyntaxKind::IN_KW),
    ("INCLUDE", SyntaxKind::INCLUDE_KW),
    ("INCLUDING", SyntaxKind::INCLUDING_KW),
    ("INDEX", SyntaxKind::INDEX_KW),
    ("INDEXED", SyntaxKind::INDEXED_KW),
    ("INHERITS", SyntaxKind::INHERITS_KW),
    ("INITIALLY", SyntaxKind::INITIALLY_KW),
    ("INNER", SyntaxKind::INNER_KW),
    ("INOUT", SyntaxKind::INOUT_KW),
    ("INSERT", SyntaxKind::INSERT_KW),
    ("INSTEAD", SyntaxKind::INSTEAD_KW),
    ("INTERSECT", SyntaxKind::INTERSECT_KW),
    ("INTERVAL", SyntaxKind::INTERVAL_KW),
    ("INTO", SyntaxKind::INTO_KW),
    ("INVISIBLE", SyntaxKind::INVISIBLE_KW),
    ("INVOKER", SyntaxKind::INVOKER_KW),
    ("IS", SyntaxKind::IS_KW),
    ("ISNULL", SyntaxKind::ISNULL_KW),
    ("ISOLATION", SyntaxKind::ISOLATION_KW),
    ("ITERATE", SyntaxKind::ITERATE_KW),
    ("JOIN", SyntaxKind::JOIN_KW),
    ("JSON", SyntaxKind::JSON_KW),
    ("KEEP", SyntaxKind::KEEP_KW),
    ("KEY", SyntaxKind::KEY_KW),
    ("KEYS", SyntaxKind::KEYS_KW),
    ("KILL", SyntaxKind::KILL_KW),
    ("LANGUAGE", SyntaxKind::LANGUAGE_KW),
    ("LAST", SyntaxKind::LAST_KW),
    ("LATERAL", SyntaxKind::LATERAL_KW),
    ("LEADING", SyntaxKind::LEADING_KW),
    ("LEAVE", SyntaxKind::LEAVE_KW),
    ("LEFT", SyntaxKind::LEFT_KW),
    ("LEVEL", SyntaxKind::LEVEL_KW),
    ("LIKE", SyntaxKind::LIKE_KW),
    ("LIMIT", SyntaxKind::LIMIT_KW),
    ("LISTEN", SyntaxKind::LISTEN_KW),
    ("LOAD", SyntaxKind::LOAD_KW),
    ("LOCAL", SyntaxKind::LOCAL_KW),
    ("LOCALTIME", SyntaxKind::LOCALTIME_KW),
    ("LOCALTIMESTAMP", SyntaxKind::LOCALTIMESTAMP_KW),
    ("LOCK", SyntaxKind::LOCK_KW),
    ("LOCKED", SyntaxKind::LOCKED_KW),
    ("LOOP", SyntaxKind::LOOP_KW),
    ("LOW_PRIORITY", SyntaxKind::LOW_PRIORITY_KW),
    ("MATCH", SyntaxKind::MATCH_KW),
    ("MATCHED", SyntaxKind::MATCHED_KW),
    ("MATERIALIZED", SyntaxKind::MATERIALIZED_KW),
    ("MEMBER", SyntaxKind::MEMBER_KW),
    ("MERGE", SyntaxKind::MERGE_KW),
    ("MICROSECOND", SyntaxKind::MICROSECOND_KW),
    ("MINUTE", SyntaxKind::MINUTE_KW),
    ("MINUTE_MICROSECOND", SyntaxKind::MINUTE_MICROSECOND_KW),
    ("MINUTE_SECOND", SyntaxKind::MINUTE_SECOND_KW),
    ("MOD", SyntaxKind::MOD_KW),
    ("MODE", SyntaxKind::MODE_KW),
    ("MODIFY", SyntaxKind::MODIFY_KW),
    ("MONTH", SyntaxKind::MONTH_KW),
    ("MOVE", SyntaxKind::MOVE_KW),
    ("NAMES", SyntaxKind::NAMES_KW),
    ("NATIONAL", SyntaxKind::NATIONAL_KW),
    ("NATURAL", SyntaxKind::NATURAL_KW),
    ("NESTED", SyntaxKind::NESTED_KW),
    ("NEXT", SyntaxKind::NEXT_KW),
    ("NO", SyntaxKind::NO_KW),
    ("NOT", SyntaxKind::NOT_KW),
    ("NOTHING", SyntaxKind::NOTHING_KW),
    ("NOTIFY", SyntaxKind::NOTIFY_KW),
    ("NOTNULL", SyntaxKind::NOTNULL_KW),
    ("NOWAIT", SyntaxKind::NOWAIT_KW),
    ("NULL", SyntaxKind::NULL_KW),
    ("NULLS", SyntaxKind::NULLS_KW),
    ("OBJECT", SyntaxKind::OBJECT_KW),
    ("OF", SyntaxKind::OF_KW),
    ("OFFSET", SyntaxKind::OFFSET_KW),
    ("OMIT", SyntaxKind::OMIT_KW),
    ("ON", SyntaxKind::ON_KW),
    ("ONLY", SyntaxKind::ONLY_KW),
    ("OPEN", SyntaxKind::OPEN_KW),
    ("OPERATOR", SyntaxKind::OPERATOR_KW),
    ("OPTIMIZE", SyntaxKind::OPTIMIZE_KW),
    ("OPTION", SyntaxKind::OPTION_KW),
    ("OR", SyntaxKind::OR_KW),
    ("ORDER", SyntaxKind::ORDER_KW),
    ("ORDINALITY", SyntaxKind::ORDINALITY_KW),
    ("OTHERS", SyntaxKind::OTHERS_KW),
    ("OUT", SyntaxKind::OUT_KW),
    ("OUTER", SyntaxKind::OUTER_KW),
    ("OVER", SyntaxKind::OVER_KW),
    ("OVERLAPS", SyntaxKind::OVERLAPS_KW),
    ("OVERRIDING", SyntaxKind::OVERRIDING_KW),
    ("OWNED", SyntaxKind::OWNED_KW),
    ("OWNER", SyntaxKind::OWNER_KW),
    ("PARTITION", SyntaxKind::PARTITION_KW),
    ("PASSING", SyntaxKind::PASSING_KW),
    ("PATH", SyntaxKind::PATH_KW),
    ("PERCENT", SyntaxKind::PERCENT_KW),
    ("PERSIST", SyntaxKind::PERSIST_KW),
    ("PERSIST_ONLY", SyntaxKind::PERSIST_ONLY_KW),
    ("PLACING", SyntaxKind::PLACING_KW),
    ("PLAN", SyntaxKind::PLAN_KW),
    ("PRAGMA", SyntaxKind::PRAGMA_KW),
    ("PRECEDES", SyntaxKind::PRECEDES_KW),
    ("PRECEDING", SyntaxKind::PRECEDING_KW),
    ("PRECISION", SyntaxKind::PRECISION_KW),
    ("PREPARE", SyntaxKind::PREPARE_KW),
    ("PRIMARY", SyntaxKind::PRIMARY_KW),
    ("PROCEDURE", SyntaxKind::PROCEDURE_KW),
    ("QUALIFY", SyntaxKind::QUALIFY_KW),
    ("QUARTER", SyntaxKind::QUARTER_KW),
    ("QUERY", SyntaxKind::QUERY_KW),
    ("QUICK", SyntaxKind::QUICK_KW),
    ("QUOTES", SyntaxKind::QUOTES_KW),
    ("RANGE", SyntaxKind::RANGE_KW),
    ("READ", SyntaxKind::READ_KW),
    ("RECURSIVE", SyntaxKind::RECURSIVE_KW),
    ("REFERENCES", SyntaxKind::REFERENCES_KW),
    ("REFERENCING", SyntaxKind::REFERENCING_KW),
    ("REFRESH", SyntaxKind::REFRESH_KW),
    ("REGEXP", SyntaxKind::REGEXP_KW),
    ("REINDEX", SyntaxKind::REINDEX_KW),
    ("RELEASE", SyntaxKind::RELEASE_KW),
    ("RENAME", SyntaxKind::RENAME_KW),
    ("REPAIR", SyntaxKind::REPAIR_KW),
    ("REPEAT", SyntaxKind::REPEAT_KW),
    ("REPEATABLE", SyntaxKind::REPEATABLE_KW),
    ("REPLACE", SyntaxKind::REPLACE_KW),
    ("RESET", SyntaxKind::RESET_KW),
    ("RESIGNAL", SyntaxKind::RESIGNAL_KW),
    ("RESTART", SyntaxKind::RESTART_KW),
    ("RESTRICT", SyntaxKind::RESTRICT_KW),
    ("RETURN", SyntaxKind::RETURN_KW),
    ("RETURNING", SyntaxKind::RETURNING_KW),
    ("RETURNS", SyntaxKind::RETURNS_KW),
    ("REVOKE", SyntaxKind::REVOKE_KW),
    ("RIGHT", SyntaxKind::RIGHT_KW),
    ("RLIKE", SyntaxKind::RLIKE_KW),
    ("ROLE", SyntaxKind::ROLE_KW),
    ("ROLLBACK", SyntaxKind::ROLLBACK_KW),
    ("ROLLUP", SyntaxKind::ROLLUP_KW),
    ("ROW", SyntaxKind::ROW_KW),
    ("ROWID", SyntaxKind::ROWID_KW),
    ("ROWS", SyntaxKind::ROWS_KW),
    ("SAVEPOINT", SyntaxKind::SAVEPOINT_KW),
    ("SCALAR", SyntaxKind::SCALAR_KW),
    ("SCHEMA", SyntaxKind::SCHEMA_KW),
    ("SEARCH", SyntaxKind::SEARCH_KW),
    ("SECOND", SyntaxKind::SECOND_KW),
    ("SECOND_MICROSECOND", SyntaxKind::SECOND_MICROSECOND_KW),
    ("SECURITY", SyntaxKind::SECURITY_KW),
    ("SELECT", SyntaxKind::SELECT_KW),
    ("SEPARATOR", SyntaxKind::SEPARATOR_KW),
    ("SEQUENCE", SyntaxKind::SEQUENCE_KW),
    ("SERIALIZABLE", SyntaxKind::SERIALIZABLE_KW),
    ("SESSION", SyntaxKind::SESSION_KW),
    ("SESSION_USER", SyntaxKind::SESSION_USER_KW),
    ("SET", SyntaxKind::SET_KW),
    ("SETOF", SyntaxKind::SETOF_KW),
    ("SETS", SyntaxKind::SETS_KW),
    ("SHARE", SyntaxKind::SHARE_KW),
    ("SHOW", SyntaxKind::SHOW_KW),
    ("SIGNAL", SyntaxKind::SIGNAL_KW),
    ("SIGNED", SyntaxKind::SIGNED_KW),
    ("SIMILAR", SyntaxKind::SIMILAR_KW),
    ("SKIP", SyntaxKind::SKIP_KW),
    ("SOME", SyntaxKind::SOME_KW),
    ("SOUNDS", SyntaxKind::SOUNDS_KW),
    ("SPATIAL", SyntaxKind::SPATIAL_KW),
    ("SQL", SyntaxKind::SQL_KW),
    ("SQL_CALC_FOUND_ROWS", SyntaxKind::SQL_CALC_FOUND_ROWS_KW),
    ("START", SyntaxKind::START_KW),
    ("STATEMENT", SyntaxKind::STATEMENT_KW),
    ("STDIN", SyntaxKind::STDIN_KW),
    ("STDOUT", SyntaxKind::STDOUT_KW),
    ("STORAGE", SyntaxKind::STORAGE_KW),
    ("STORED", SyntaxKind::STORED_KW),
    ("STRAIGHT_JOIN", SyntaxKind::STRAIGHT_JOIN_KW),
    ("STRICT", SyntaxKind::STRICT_KW),
    ("SYMMETRIC", SyntaxKind::SYMMETRIC_KW),
    ("SYSTEM_USER", SyntaxKind::SYSTEM_USER_KW),
    ("TABLE", SyntaxKind::TABLE_KW),
    ("TABLESAMPLE", SyntaxKind::TABLESAMPLE_KW),
    ("TEMP", SyntaxKind::TEMP_KW),
    ("TEMPORARY", SyntaxKind::TEMPORARY_KW),
    ("THEN", SyntaxKind::THEN_KW),
    ("TIES", SyntaxKind::TIES_KW),
    ("TIME", SyntaxKind::TIME_KW),
    ("TIMESTAMP", SyntaxKind::TIMESTAMP_KW),
    ("TO", SyntaxKind::TO_KW),
    ("TRAILING", SyntaxKind::TRAILING_KW),
    ("TRANSACTION", SyntaxKind::TRANSACTION_KW),
    ("TRIGGER", SyntaxKind::TRIGGER_KW),
    ("TRUE", SyntaxKind::TRUE_KW),
    ("TRUNCATE", SyntaxKind::TRUNCATE_KW),
    ("TYPE", SyntaxKind::TYPE_KW),
    ("UNBOUNDED", SyntaxKind::UNBOUNDED_KW),
    ("UNCOMMITTED", SyntaxKind::UNCOMMITTED_KW),
    ("UNCONDITIONAL", SyntaxKind::UNCONDITIONAL_KW),
    ("UNION", SyntaxKind::UNION_KW),
    ("UNIQUE", SyntaxKind::UNIQUE_KW),
    ("UNKNOWN", SyntaxKind::UNKNOWN_KW),
    ("UNLISTEN", SyntaxKind::UNLISTEN_KW),
    ("UNLOCK", SyntaxKind::UNLOCK_KW),
    ("UNLOGGED", SyntaxKind::UNLOGGED_KW),
    ("UNSIGNED", SyntaxKind::UNSIGNED_KW),
    ("UNTIL", SyntaxKind::UNTIL_KW),
    ("UPDATE", SyntaxKind::UPDATE_KW),
    ("USE", SyntaxKind::USE_KW),
    ("USER", SyntaxKind::USER_KW),
    ("USING", SyntaxKind::USING_KW),
    ("VACUUM", SyntaxKind::VACUUM_KW),
    ("VALUE", SyntaxKind::VALUE_KW),
    ("VALUES", SyntaxKind::VALUES_KW),
    ("VARIADIC", SyntaxKind::VARIADIC_KW),
    ("VARYING", SyntaxKind::VARYING_KW),
    ("VIEW", SyntaxKind::VIEW_KW),
    ("VIRTUAL", SyntaxKind::VIRTUAL_KW),
    ("VISIBLE", SyntaxKind::VISIBLE_KW),
    ("WEEK", SyntaxKind::WEEK_KW),
    ("WHEN", SyntaxKind::WHEN_KW),
    ("WHERE", SyntaxKind::WHERE_KW),
    ("WHILE", SyntaxKind::WHILE_KW),
    ("WINDOW", SyntaxKind::WINDOW_KW),
    ("WITH", SyntaxKind::WITH_KW),
    ("WITHIN", SyntaxKind::WITHIN_KW),
    ("WITHOUT", SyntaxKind::WITHOUT_KW),
    ("WORK", SyntaxKind::WORK_KW),
    ("WRAPPER", SyntaxKind::WRAPPER_KW),
    ("WRITE", SyntaxKind::WRITE_KW),
    ("XOR", SyntaxKind::XOR_KW),
    ("YEAR", SyntaxKind::YEAR_KW),
    ("YEAR_MONTH", SyntaxKind::YEAR_MONTH_KW),
    ("ZEROFILL", SyntaxKind::ZEROFILL_KW),
    ("ZONE", SyntaxKind::ZONE_KW),
];

/// The length of the longest keyword, past which a word is never one.
pub(crate) const LONGEST_KEYWORD: usize = 19;

impl SyntaxKind {
    /// Whitespace and comments, which the parser keeps in the tree but never looks at.
    pub fn is_trivia(self) -> bool {
        matches!(
            self,
            SyntaxKind::WHITESPACE | SyntaxKind::LINE_COMMENT | SyntaxKind::BLOCK_COMMENT
        )
    }

    /// A word the grammar looks for. A keyword that names something, as `date` in `SELECT date FROM
    /// t`, keeps its kind and stands in a `NAME` node.
    pub fn is_keyword(self) -> bool {
        self >= SyntaxKind::ABORT_KW && self <= SyntaxKind::ZONE_KW
    }

    /// A token as opposed to a node.
    pub fn is_token(self) -> bool {
        self < SyntaxKind::SOURCE_FILE
    }

    /// A quoted or unquoted identifier.
    pub fn is_identifier(self) -> bool {
        matches!(
            self,
            SyntaxKind::IDENT | SyntaxKind::QUOTED_IDENT | SyntaxKind::BACKTICK_IDENT | SyntaxKind::BRACKET_IDENT
        )
    }

    /// A string literal of any form.
    pub fn is_string(self) -> bool {
        matches!(
            self,
            SyntaxKind::STRING
                | SyntaxKind::ESCAPE_STRING
                | SyntaxKind::NATIONAL_STRING
                | SyntaxKind::UNICODE_STRING
                | SyntaxKind::BIT_STRING
                | SyntaxKind::HEX_STRING
                | SyntaxKind::DOLLAR_STRING
        )
    }

    /// The keyword spelled `word`, in any case.
    pub fn from_keyword(word: &str) -> Option<SyntaxKind> {
        if word.len() > LONGEST_KEYWORD || !word.is_ascii() {
            return None;
        }
        let mut buffer = [0u8; LONGEST_KEYWORD];
        let upper = &mut buffer[..word.len()];
        upper.copy_from_slice(word.as_bytes());
        upper.make_ascii_uppercase();
        KEYWORDS
            .binary_search_by(|(spelling, _)| spelling.as_bytes().cmp(upper))
            .ok()
            .map(|index| KEYWORDS[index].1)
    }
}

impl lsc_syntax::TokenKind for SyntaxKind {
    const EOF: SyntaxKind = SyntaxKind::EOF;
    const ERROR: SyntaxKind = SyntaxKind::ERROR;

    fn is_trivia(self) -> bool {
        SyntaxKind::is_trivia(self)
    }

    fn is_whitespace(self) -> bool {
        self == SyntaxKind::WHITESPACE
    }
}

/// The rowan language marker for SQL.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum SqlLanguage {}

impl rowan::Language for SqlLanguage {
    type Kind = SyntaxKind;

    fn kind_from_raw(raw: rowan::SyntaxKind) -> SyntaxKind {
        SyntaxKind::ALL[raw.0 as usize]
    }

    fn kind_to_raw(kind: SyntaxKind) -> rowan::SyntaxKind {
        rowan::SyntaxKind(kind as u16)
    }
}

pub type SyntaxNode = rowan::SyntaxNode<SqlLanguage>;
pub type SyntaxToken = rowan::SyntaxToken<SqlLanguage>;
pub type SyntaxElement = rowan::SyntaxElement<SqlLanguage>;
